on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy application
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build image
        env:
          RESOURCE_NAME: ${{ secrets.RESOURCE_NAME }}
        run: make build
      - name: Login to container registry
        env:
          RESOURCE_NAME: ${{ secrets.RESOURCE_NAME }}
        run: make registry-login
      - name: Push image
        env:
          RESOURCE_NAME: ${{ secrets.RESOURCE_NAME }}
        run: make push
      - name: Get AKS credentials
        env:
          RESOURCE_NAME: ${{ secrets.RESOURCE_NAME }}
        run: |
          az aks get-credentials \
            --resource-group $RESOURCE_NAME \
            --name $RESOURCE_NAME \
            --overwrite-existing
      - name: Deploy application
        env:
          RESOURCE_NAME: ${{ secrets.RESOURCE_NAME }}
        run: make deploy
